#!/usr/bin/env node
import { randomUUID, createHash } from "node:crypto";
import { link, mkdir, open, readFile, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CALL_CAP, ROLE_IDENTITIES, TIMEOUT_POLICY, buildRequest, classifyCall, fixtureInput } from "./contract.mjs";
import { buildEvidence, expectedHealth, sourceIdentity, runtimeIdentity, verifyEvidence } from "./evidence-v2.mjs";
import { APPROVAL_VERSION, costForUsage, createPlan, deriveManifests, validateApproval } from "./qualification.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../.."); const OUTPUT = path.join(ROOT, "spikes/generation-qualification/results");
const safeBase = (value) => typeof value === "string" && /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value);
const canonical = (value) => Buffer.from(`${JSON.stringify(value, null, 2)}\n`);
async function atomic(file, bytes, { replace = false } = {}) { const temporary = `${file}.${process.pid}.${randomUUID()}.tmp`; await writeFile(temporary, bytes, { flag: "wx" }); try { if (replace) await rename(temporary, file); else { await link(temporary, file); await unlink(temporary); } } catch (error) { await unlink(temporary).catch(() => {}); throw error; } }
export async function publishArtifactSet(directory, baseName, members, hooks = {}) {
  const created = []; try { for (const [name, bytes] of Object.entries(members)) { hooks.beforeMember?.(name); await atomic(path.join(directory, name), bytes); created.push(path.join(directory, name)); } const files = Object.entries(members).map(([name, bytes]) => ({ name, bytes: bytes.byteLength, sha256: createHash("sha256").update(bytes).digest("hex") })); const marker = path.join(directory, `${baseName}.complete.json`); hooks.beforeMarker?.(); await atomic(marker, canonical({ schema_version: "oddspark.generation-qualification-complete/v1", basename: baseName, files })); created.push(marker); return marker; } catch (error) { for (const file of created.reverse()) await unlink(file).catch(() => {}); throw error; }
}
export async function completeSpendReceipt(receiptPath, receipt, records, markerPath, completedAt = new Date().toISOString()) { const actual_spend_usd = records.reduce((sum, record) => sum + (record.cost_usd ?? 0), 0); const completed = { ...receipt, state: "completed", completed_at: completedAt, calls_made: records.length, actual_spend_usd, completion_marker: path.basename(markerPath) }; await atomic(receiptPath, canonical(completed), { replace: true }); return completed; }
async function fetchJson(url, options, timeoutMs) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetch(url, { ...options, redirect: "error", signal: controller.signal }); let body = null; try { body = await response.json(); } catch {} return { response, body }; } finally { clearTimeout(timer); } }
function loopback(value) { const url = new URL(value); if (url.protocol !== "http:" || !["127.0.0.1", "localhost", "[::1]"].includes(url.hostname) || url.username || url.password || url.search || url.hash) throw new TypeError("adapter URL must be credential-free loopback HTTP"); return url; }
async function invoke(base, request) {
  const started_at = new Date().toISOString(); const start = performance.now();
  try { const { response, body } = await fetchJson(new URL("run", base), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(request.body) }, TIMEOUT_POLICY.adapter_timeout_ms); return { started_at, ended_at: new Date().toISOString(), latency_ms: Math.round(performance.now() - start), call_state: response.ok && body?.ok === true ? "received" : "provider_error", output: body?.output ?? null, usage: body?.usage ?? null }; }
  catch (error) { return { started_at, ended_at: new Date().toISOString(), latency_ms: Math.round(performance.now() - start), call_state: error?.name === "AbortError" ? "timeout" : "provider_error", output: null, usage: null }; }
}
function retain(kind, index, request, call) { const classified = classifyCall(call); const usage = call.usage ?? null; const cost = costForUsage(request.resolved_model, usage); if (cost === undefined) throw new TypeError("adapter usage is malformed"); return { kind, role: request.role, resolved_model: request.resolved_model, index, started_at: call.started_at, ended_at: call.ended_at, latency_ms: call.latency_ms, call_state: call.call_state, classification: classified.classification, candidate: classified.candidate, candidate_ref: classified.candidate_ref, issues: classified.issues, retained: classified.retained, retained_sha256: classified.retained_sha256, retained_bytes: classified.retained_bytes, usage, cost_usd: cost, request_sha256: request.request_sha256 }; }
export async function executeSchedule(requests, invokeCall) { const records = []; for (const request of requests) { const probe = retain("probe", 1, request, await invokeCall(request)); records.push(probe); if (probe.classification !== "direct_valid") continue; for (let index = 1; index <= 20; index += 1) records.push(retain("trial", index, request, await invokeCall(request))); } if (records.length > CALL_CAP) throw new Error("call cap exceeded"); return records; }
async function commandPlan() { await mkdir(OUTPUT, { recursive: true }); const id = process.argv[3] ?? `generation-${new Date().toISOString().replace(/[:.]/g, "-")}`; if (!safeBase(id)) throw new TypeError("plan id is unsafe"); const plan = await createPlan({ approval_run_id: id, input: fixtureInput(), authority: { account_profile: "operator-reviewed-profile", credential_path: "wrangler-remote-binding", headroom_confirmed: true } }); const file = path.join(OUTPUT, `${id}.plan.json`); await atomic(file, canonical(plan)); console.log(file); }
async function commandLive() {
  const planFile = process.argv[3]; const approvalFile = process.argv[4]; if (!planFile || !approvalFile) throw new Error("Usage: run.mjs live <plan.json> <approval.json>");
  if (process.env.CI || !process.stdin.isTTY || !process.stdout.isTTY) throw new Error("live qualification requires an interactive TTY and refuses CI");
  const plan = JSON.parse(await readFile(planFile, "utf8")); const approval = JSON.parse(await readFile(approvalFile, "utf8")); if (plan.plan_ref !== (await createPlan({ approval_run_id: plan.approval_run_id, created_at: plan.created_at, input: plan.input, authority: plan.authority })).plan_ref) throw new Error("plan bytes or frozen source identities drifted");
  const approvalCheck = validateApproval(approval, plan); if (!approvalCheck.valid) throw new Error(approvalCheck.errors.join("; "));
  const base = loopback(process.env.ODDSPARK_GENERATION_ADAPTER_URL ?? "http://127.0.0.1:8789/"); const sources = await sourceIdentity(); const runtime = await runtimeIdentity(); const expected = expectedHealth(sources, runtime);
  const { response, body } = await fetchJson(new URL("health", base), {}, TIMEOUT_POLICY.preflight_timeout_ms); if (!response.ok || JSON.stringify(body) !== JSON.stringify(expected)) throw new Error("adapter health identity mismatch; zero inference calls made");
  await mkdir(OUTPUT, { recursive: true }); const receiptPath = path.join(OUTPUT, `${plan.approval_run_id}.spend-receipt.json`); const receipt = { schema_version: "oddspark.generation-spend-receipt/v1", plan_ref: plan.plan_ref, approval_run_id: plan.approval_run_id, reserved_at: new Date().toISOString(), call_cap: CALL_CAP, state: "reserved-before-inference" }; const handle = await open(receiptPath, "wx"); await handle.writeFile(canonical(receipt)); await handle.close();
  const started_at = new Date().toISOString(); const records = await executeSchedule(plan.requests, (request) => invoke(base, request)); const ended_at = new Date().toISOString(); const adapter = { endpoint: base.href, expected_health: expected, observed_health: body, identity_match: true };
  const evidence = await buildEvidence({ run: { id: randomUUID(), started_at, ended_at, call_cap: CALL_CAP, calls_made: records.length }, plan, input: plan.input, records, adapter, approval, pricing: plan.estimate }); const verification = await verifyEvidence(evidence); if (!verification.valid) throw new Error(`self-verification failed: ${verification.errors.join("; ")}`);
  const qualification = deriveManifests(evidence, verification.predicate_results); const baseName = `${plan.approval_run_id}-${evidence.run.id}`; const members = { [`${baseName}.evidence.json`]: canonical(evidence), [`${baseName}.report.md`]: Buffer.from(evidence.report), [`${baseName}.qualification.json`]: canonical(qualification) };
  const marker = await publishArtifactSet(OUTPUT, baseName, members); await completeSpendReceipt(receiptPath, receipt, records, marker); console.log(marker);
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const command = process.argv[2]; if (command === "plan") await commandPlan(); else if (command === "live") await commandLive(); else { console.error("Usage: run.mjs <plan [id]|live <plan> <approval>>"); process.exitCode = 2; }
}
