#!/usr/bin/env node
import { randomUUID, createHash } from "node:crypto";
import { constants } from "node:fs";
import { link, lstat, mkdir, mkdtemp, open, readFile, rename, unlink } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CALL_CAP, ROLE_IDENTITIES, TIMEOUT_POLICY, buildRequest, classifyCall, fixtureInput } from "./contract.mjs";
import { buildEvidence, expectedHealth, sourceIdentity, runtimeIdentity, verifyEvidence } from "./evidence-v2.mjs";
import { APPROVAL_VERSION, costForUsage, createPlan, deriveManifests, validateApproval } from "./qualification.mjs";
import { findPriorOperationalRecovery } from "./recovery-finder.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../.."); const OUTPUT = path.join(ROOT, "spikes/generation-qualification/results");
const safeBase = (value) => typeof value === "string" && /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value);
const canonical = (value) => Buffer.from(`${JSON.stringify(value, null, 2)}\n`);
async function syncDirectory(directory) { const handle = await open(directory, "r"); try { await handle.sync(); } finally { await handle.close(); } }
export async function atomic(file, bytes, { replace = false, sync = syncDirectory } = {}) { const directory = path.dirname(file); const temporary = path.join(directory, `.${path.basename(file)}.${process.pid}.${randomUUID()}.tmp`); const handle = await open(temporary, "wx", 0o600); let installed = false; try { await handle.writeFile(bytes); await handle.sync(); } finally { await handle.close(); } try { if (replace) await rename(temporary, file); else { await link(temporary, file); await unlink(temporary); } installed = true; await sync(directory); } catch (error) { await unlink(temporary).catch(() => {}); if (installed && !replace) await unlink(file).catch(() => {}); await syncDirectory(directory).catch(() => {}); throw error; } }
export const STALE_LOCK_AGE_MS = 15 * 60 * 1000;
async function recoverStaleLock(lockPath, { now = Date.now(), alive = (pid) => { try { process.kill(pid, 0); return true; } catch (error) { if (error.code === "ESRCH") return false; throw error; } } } = {}) { const before = await lstat(lockPath); if (!before.isFile() || before.isSymbolicLink()) throw new Error("cycle lock is not a regular file"); const handle = await open(lockPath, constants.O_RDONLY | constants.O_NOFOLLOW); let lock; try { lock = JSON.parse(await handle.readFile("utf8")); const opened = await handle.stat(); if (opened.dev !== before.dev || opened.ino !== before.ino || opened.size !== before.size || opened.mtimeMs !== before.mtimeMs) throw new Error("cycle lock changed while inspected"); } finally { await handle.close(); } const keys = ["schema_version", "pid", "uid", "hostname", "acquired_at", "nonce"]; if (!lock || Object.keys(lock).some((key) => !keys.includes(key) && key !== "approval_run_id") || lock.schema_version !== "oddspark.generation-cycle-lock/v1" || !Number.isSafeInteger(lock.pid) || lock.pid < 1 || lock.uid !== (process.getuid?.() ?? null) || lock.hostname !== os.hostname() || !canonicalTime(lock.acquired_at) || !/^[0-9a-f-]{36}$/.test(lock.nonce)) throw new Error("cycle lock ownership is unknown"); if (now - Date.parse(lock.acquired_at) <= STALE_LOCK_AGE_MS || alive(lock.pid)) throw new Error("cycle lock is live or not old enough for recovery"); const current = await lstat(lockPath); if (current.dev !== before.dev || current.ino !== before.ino) throw new Error("cycle lock was replaced during stale recovery"); await unlink(lockPath); await syncDirectory(path.dirname(lockPath)); return true; }
const canonicalTime = (value) => typeof value === "string" && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;
export async function acquireCycleLock(directory, owner = {}, policy = {}) { await mkdir(directory, { recursive: true }); const lockPath = path.join(directory, ".generation-llama-cycle.lock"); const create = async () => { const lock = { schema_version: "oddspark.generation-cycle-lock/v1", pid: process.pid, uid: process.getuid?.() ?? null, hostname: os.hostname(), acquired_at: new Date().toISOString(), nonce: randomUUID(), ...owner }; const handle = await open(lockPath, "wx", 0o600); try { await handle.writeFile(canonical(lock)); await handle.sync(); } catch (error) { await handle.close().catch(() => {}); await unlink(lockPath).catch(() => {}); await syncDirectory(directory).catch(() => {}); throw error; } const stat = await handle.stat(); await handle.close(); await syncDirectory(directory); return { lockPath, dev: stat.dev, ino: stat.ino, nonce: lock.nonce }; }; try { return await create(); } catch (error) { if (error.code !== "EEXIST" || policy.recoverStale !== true) throw error; await recoverStaleLock(lockPath, policy); return create(); } }
export async function releaseCycleLock(acquired) { const current = await lstat(acquired.lockPath).catch((error) => error?.code === "ENOENT" ? null : Promise.reject(error)); if (!current) return false; if (current.isSymbolicLink() || current.dev !== acquired.dev || current.ino !== acquired.ino) throw new Error("cycle lock was replaced; refusing to release successor"); const handle = await open(acquired.lockPath, constants.O_RDONLY | constants.O_NOFOLLOW); let retained; try { retained = JSON.parse(await handle.readFile("utf8")); const opened = await handle.stat(); if (opened.dev !== acquired.dev || opened.ino !== acquired.ino) throw new Error("cycle lock changed before release"); } finally { await handle.close(); } if (retained.nonce !== acquired.nonce) throw new Error("cycle lock nonce changed; refusing release"); await unlink(acquired.lockPath); await syncDirectory(path.dirname(acquired.lockPath)); return true; }
export async function verifyPublishedArtifactSet(directory, baseName, members, semanticVerify = async () => ({ valid: true, errors: [] })) { if (!safeBase(baseName)) throw new TypeError("publication basename is unsafe"); const markerName = `${baseName}.complete.json`; const markerBytes = await readFile(path.join(directory, markerName)); const marker = JSON.parse(markerBytes); const entries = Object.entries(members); const expected = entries.map(([name, bytes]) => ({ name, bytes: bytes.byteLength, sha256: createHash("sha256").update(bytes).digest("hex") })); if (marker.schema_version !== "oddspark.generation-qualification-complete/v1" || marker.basename !== baseName || JSON.stringify(marker.files) !== JSON.stringify(expected)) throw new Error("completion marker binding mismatch"); const reread = {}; for (const [index, [name]] of entries.entries()) { const bytes = await readFile(path.join(directory, name)); const binding = marker.files[index]; if (bytes.byteLength !== binding.bytes || createHash("sha256").update(bytes).digest("hex") !== binding.sha256) throw new Error(`published member bytes drifted: ${name}`); reread[name] = bytes; } const verification = await semanticVerify(reread, marker); if (verification?.valid !== true) throw new Error(`published artifact semantic verification failed: ${(verification?.errors ?? []).join("; ")}`); return { marker, members: reread, verification }; }
export async function publishArtifactSet(directory, baseName, members, hooks = {}) {
  if (!safeBase(baseName)) throw new TypeError("publication basename is unsafe");
  const entries = Object.entries(members); if (entries.length === 0 || entries.some(([name, bytes]) => !safeBase(name) || path.basename(name) !== name || !Buffer.isBuffer(bytes))) throw new TypeError("publication member is unsafe");
  const created = []; try { for (const [name, bytes] of entries) { hooks.beforeMember?.(name); await atomic(path.join(directory, name), bytes); created.push(path.join(directory, name)); } const files = entries.map(([name, bytes]) => ({ name, bytes: bytes.byteLength, sha256: createHash("sha256").update(bytes).digest("hex") })); const marker = path.join(directory, `${baseName}.complete.json`); hooks.beforeMarker?.(); await atomic(marker, canonical({ schema_version: "oddspark.generation-qualification-complete/v1", basename: baseName, files })); created.push(marker); await verifyPublishedArtifactSet(directory, baseName, members, hooks.semanticVerify); return marker; } catch (error) { for (const file of created.reverse()) await unlink(file).catch(() => {}); await syncDirectory(directory).catch(() => {}); throw error; }
}
export async function completeSpendReceipt(receiptPath, receipt, records, markerPath, completedAt = new Date().toISOString()) { const costs = records.map(({ cost_usd }) => cost_usd); const actual_spend_usd = costs.every((cost) => typeof cost === "number" && Number.isFinite(cost)) ? costs.reduce((sum, cost) => sum + cost, 0) : null; const completed = { ...receipt, state: "completed-spent", completed_at: completedAt, calls_made: records.length, actual_spend_usd, actual_spend_known: actual_spend_usd !== null, completion_marker: path.basename(markerPath) }; await atomic(receiptPath, canonical(completed), { replace: true }); return completed; }
export async function terminalizeFailure(receiptPath, receipt, callsStarted, originalError, write = atomic) { const terminal = { ...receipt, calls_started: callsStarted, state: "consumed_incomplete", failed_at: new Date().toISOString(), original_error: String(originalError?.message ?? originalError) }; try { await write(receiptPath, canonical(terminal), { replace: true }); } catch (terminalError) { throw new AggregateError([originalError, terminalError], `qualification failed and terminalization failed: ${String(originalError?.message ?? originalError)}; ${String(terminalError?.message ?? terminalError)}`); } return terminal; }
async function fetchJson(url, options, timeoutMs) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetch(url, { ...options, redirect: "error", signal: controller.signal }); let body = null; try { body = await response.json(); } catch {} return { response, body }; } finally { clearTimeout(timer); } }
function loopback(value) { const url = new URL(value); if (url.protocol !== "http:" || !["127.0.0.1", "localhost", "[::1]"].includes(url.hostname) || url.username || url.password || url.search || url.hash) throw new TypeError("adapter URL must be credential-free loopback HTTP"); return url; }
async function invoke(base, request, authority) {
  const started_at = new Date().toISOString(); const start = performance.now();
  try { const { response, body } = await fetchJson(new URL("run", base), { method: "POST", headers: { "content-type": "application/json", "x-oddspark-qualification-authority": authority }, body: JSON.stringify(request.body) }, TIMEOUT_POLICY.adapter_timeout_ms); return { started_at, ended_at: new Date().toISOString(), latency_ms: Math.round(performance.now() - start), call_state: response.ok && body?.ok === true ? "received" : "provider_error", output: body?.output ?? null, usage: body?.usage ?? null }; }
  catch (error) { return { started_at, ended_at: new Date().toISOString(), latency_ms: Math.round(performance.now() - start), call_state: error?.name === "AbortError" ? "timeout" : "provider_error", output: null, usage: null }; }
}
function retain(kind, index, attempt, request, call) { const classified = classifyCall(call); const usage = call.usage ?? null; const cost = costForUsage(request.resolved_model, usage); if (cost === undefined) throw new TypeError("adapter usage is malformed"); return { kind, role: request.role, resolved_model: request.resolved_model, index, attempt, started_at: call.started_at, ended_at: call.ended_at, latency_ms: call.latency_ms, call_state: call.call_state, classification: classified.classification, candidate: classified.candidate, candidate_ref: classified.candidate_ref, issues: classified.issues, retained: classified.retained, retained_sha256: classified.retained_sha256, retained_bytes: classified.retained_bytes, usage, cost_usd: cost, request_sha256: request.request_sha256 }; }
// One scheduled call retries only a transient terminal state (provider_error/timeout), at most once, immediately after the failed attempt; retries consume the shared call cap and the schedule stops when the cap is exhausted, leaving remaining trials absent so verification fails closed on cardinality.
export async function executeSchedule(requests, invokeCall) { const records = []; const accepted = []; const scheduled = async (kind, index, request) => { let attempt = 0; let record; do { attempt += 1; record = retain(kind, index, attempt, request, await invokeCall(request)); records.push(record); } while (TIMEOUT_POLICY.retry_states.includes(record.classification) && attempt <= TIMEOUT_POLICY.transient_retries && records.length < CALL_CAP); return record; }; for (const request of requests) { if (records.length >= CALL_CAP) break; const probe = await scheduled("probe", 1, request); if (probe.classification === "direct_valid") accepted.push(request); } for (const request of accepted) for (let index = 1; index <= 20 && records.length < CALL_CAP; index += 1) await scheduled("trial", index, request); if (records.length > CALL_CAP) throw new Error("call cap exceeded"); return records; }
export function approvalTemplate(plan) { return { schema_version: APPROVAL_VERSION, plan_ref: plan.plan_ref, approval_run_id: plan.approval_run_id, approved_at: null, approved_by: null, approved_call_cap: CALL_CAP, approved_maximum_usd: plan.estimate.maximum_usd, authorization: null }; }
export async function commandPlan(argv = process.argv.slice(3)) {
  const id = argv[0] ?? `generation-${new Date().toISOString().replace(/[:.]/g, "-")}`;
  if (!safeBase(id)) throw new TypeError("plan id is unsafe");
  const options = {}; for (let index = 1; index < argv.length; index += 1) { const token = argv[index]; if (!token.startsWith("--")) throw new TypeError("unexpected plan argument"); const key = token.slice(2).replaceAll("-", "_"); if (key === "retain") options.retain = true; else { const value = argv[++index]; if (value === undefined || value.startsWith("--")) throw new TypeError(`missing value for ${token}`); options[key] = value; } }
  if (options.account_profile !== "Hearn Systems account" || !["free", "paid"].includes(options.plan)) throw new TypeError("plan requires the reviewed account profile and --plan <free|paid>");
  const remaining = options.remaining_free_neurons === undefined ? null : Number(options.remaining_free_neurons);
  const authority = { account_profile: options.account_profile, credential_path: "wrangler-remote-binding", headroom_confirmed: true, workers_plan: options.plan, daily_free_neurons: 10_000, billing_order: "free-first-then-paid-bounded-by-plan-cap", remaining_free_neurons: options.plan === "paid" ? null : remaining };
  const plan = await createPlan({ approval_run_id: id, input: fixtureInput(), authority });
  const directory = options.retain === true ? OUTPUT : await mkdtemp(path.join(os.tmpdir(), "oddspark-generation-plan-"));
  await mkdir(directory, { recursive: true });
  const files = { [`${id}.plan.json`]: plan, [`${id}.approval-template.json`]: approvalTemplate(plan), [`${id}.execution.json`]: { schema_version: "oddspark.generation-execution-marker/v1", plan_ref: plan.plan_ref, approval: null, execution: null, allowance_consumed: false, provider_calls: 0 } };
  for (const [name, value] of Object.entries(files)) await atomic(path.join(directory, name), canonical(value));
  console.log(directory); return { directory, plan, files };
}
async function commandLive() {
  const planFile = process.argv[3]; const approvalFile = process.argv[4]; if (!planFile || !approvalFile) throw new Error("Usage: run.mjs live <plan.json> <approval.json>");
  if (process.env.CI || !process.stdin.isTTY || !process.stdout.isTTY) throw new Error("live qualification requires an interactive TTY and refuses CI");
  await mkdir(OUTPUT, { recursive: true }); const acquired = await acquireCycleLock(OUTPUT, {}, { recoverStale: true }); let receiptPath = null; let receipt = null; let callsStarted = 0; let completed = false;
  try {
    const planBytes = await readFile(planFile); const approvalBytes = await readFile(approvalFile); const plan = JSON.parse(planBytes); const approval = JSON.parse(approvalBytes); if (!planBytes.equals(canonical(plan)) || !approvalBytes.equals(canonical(approval))) throw new Error("plan and approval must be exact canonical bytes"); if (plan.plan_ref !== (await createPlan({ approval_run_id: plan.approval_run_id, created_at: plan.created_at, input: plan.input, authority: plan.authority })).plan_ref) throw new Error("plan bytes or frozen source identities drifted");
    const approvalCheck = validateApproval(approval, plan); if (!approvalCheck.valid) throw new Error(approvalCheck.errors.join("; "));
    const prior = await findPriorOperationalRecovery(OUTPUT); if (prior.allowance_consumed) throw new Error(`Llama generation cycle is ${prior.state}; owner review is required`); if (prior.plan_ref && (prior.plan_ref !== plan.plan_ref || prior.approval_run_id !== plan.approval_run_id)) throw new Error("zero-call history belongs to a different exact plan/run cycle");
    const attemptId = randomUUID(); receiptPath = path.join(OUTPUT, `${plan.approval_run_id}-${attemptId}.spend-receipt.json`); receipt = { schema_version: "oddspark.generation-spend-receipt/v1", plan_ref: plan.plan_ref, approval_sha256: createHash("sha256").update(JSON.stringify(approval)).digest("hex"), approval_run_id: plan.approval_run_id, attempt_id: attemptId, reserved_at: new Date().toISOString(), call_cap: CALL_CAP, calls_started: 0, state: "zero-call" }; await atomic(receiptPath, canonical(receipt));
    const base = loopback(process.env.ODDSPARK_GENERATION_ADAPTER_URL ?? "http://127.0.0.1:8789/"); const sources = await sourceIdentity(); const runtime = await runtimeIdentity(); const expected = expectedHealth(sources, runtime);
    const { response, body } = await fetchJson(new URL("health", base), {}, TIMEOUT_POLICY.preflight_timeout_ms); if (!response.ok || JSON.stringify(body) !== JSON.stringify(expected)) throw new Error("adapter health identity mismatch; zero inference calls made");
    const started_at = new Date().toISOString(); const authority = createHash("sha256").update(JSON.stringify(approval)).digest("hex"); const records = await executeSchedule(plan.requests, async (request) => { callsStarted += 1; receipt = { ...receipt, calls_started: callsStarted, first_call_started_at: receipt.first_call_started_at ?? new Date().toISOString(), state: "calling" }; await atomic(receiptPath, canonical(receipt), { replace: true }); return invoke(base, request, authority); }); const ended_at = new Date().toISOString(); const adapter = { endpoint: base.href, expected_health: expected, observed_health: body, identity_match: true };
    const evidence = await buildEvidence({ run: { id: receipt.attempt_id, started_at, ended_at, call_cap: CALL_CAP, calls_made: records.length }, plan, input: plan.input, records, adapter, approval, pricing: plan.estimate }); const verification = await verifyEvidence(evidence); if (!verification.valid) throw new Error(`self-verification failed: ${verification.errors.join("; ")}`);
    const qualification = await deriveManifests(evidence); const baseName = `${plan.approval_run_id}-${evidence.run.id}`; const members = { [`${baseName}.evidence.json`]: canonical(evidence), [`${baseName}.report.md`]: Buffer.from(evidence.report), [`${baseName}.qualification.json`]: canonical(qualification) };
    const semanticVerify = async (reread) => { const checked = await verifyEvidence(JSON.parse(reread[`${baseName}.evidence.json`])); let derived = null; try { derived = await deriveManifests(JSON.parse(reread[`${baseName}.evidence.json`])); } catch {} return { valid: checked.valid && reread[`${baseName}.report.md`].toString() === evidence.report && JSON.stringify(JSON.parse(reread[`${baseName}.qualification.json`])) === JSON.stringify(derived), errors: checked.errors }; }; const marker = await publishArtifactSet(OUTPUT, baseName, members, { semanticVerify }); await verifyPublishedArtifactSet(OUTPUT, baseName, members, semanticVerify); await completeSpendReceipt(receiptPath, receipt, records, marker); completed = true; console.log(marker);
  } catch (error) {
    if (!completed && receiptPath && receipt && callsStarted > 0) await terminalizeFailure(receiptPath, receipt, callsStarted, error);
    throw error;
  } finally { await releaseCycleLock(acquired); }
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const command = process.argv[2]; if (command === "plan") await commandPlan(); else if (command === "live") await commandLive(); else { console.error("Usage: run.mjs <plan <id> --account-profile <label> --plan <free|paid> [--remaining-free-neurons N] [--retain]|live <plan> <approval>>"); process.exitCode = 2; }
}
