import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, readFile, readdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { APPROVAL_VERSION, costForUsage, createPlan, deriveManifests, validateApproval } from "./qualification.mjs";
import { CALL_CAP, CANDIDATE_RESPONSE_FORMAT, GENERATION_PREDICATES, ROLE_IDENTITIES, buildRequest, classifyCall, fixtureCandidate, fixtureInput } from "./contract.mjs";
import { executeFixtures } from "./fixture-executor.mjs";
import { buildEvidence, expectedHealth, runtimeIdentity, sourceIdentity, verifyEvidence } from "./evidence-v2.mjs";
import { completeSpendReceipt, executeSchedule, publishArtifactSet } from "./run.mjs";
import { verifyBytes } from "./verify-v2.mjs";

const at = (offset) => new Date(Date.parse("2026-08-18T20:00:00.000Z") + offset).toISOString();
function retained(kind, index, request, call, offset) { const result = classifyCall(call); const usage = { input_tokens: 1, output_tokens: 1 }; return { kind, role: request.role, resolved_model: request.resolved_model, index, started_at: at(offset), ended_at: at(offset + 1), latency_ms: 1, call_state: call.call_state, classification: result.classification, candidate: result.candidate, candidate_ref: result.candidate_ref, issues: result.issues, retained: result.retained, retained_sha256: result.retained_sha256, retained_bytes: result.retained_bytes, usage, cost_usd: costForUsage(request.resolved_model, usage), request_sha256: request.request_sha256 }; }
async function validEvidence({ primaryFailures = 0 } = {}) {
  const input = fixtureInput(); const requests = ROLE_IDENTITIES.map((role) => buildRequest(role, input)); const records = []; let offset = 0;
  for (const request of requests) { records.push(retained("probe", 1, request, { call_state: "received", output: fixtureCandidate() }, offset += 2)); for (let index = 1; index <= 20; index += 1) { const failed = request.role === "primary" && index <= primaryFailures; records.push(retained("trial", index, request, failed ? { call_state: "provider_error" } : { call_state: "received", output: fixtureCandidate() }, offset += 2)); } }
  const sources = await sourceIdentity(); const runtime = await runtimeIdentity(); const plan = await createPlan({ approval_run_id: "test", created_at: at(0), input, authority: { account_profile: "fixture", credential_path: "wrangler-remote-binding", headroom_confirmed: true } }); const approval = { schema_version: APPROVAL_VERSION, plan_ref: plan.plan_ref, approval_run_id: "test", approved_at: at(0), approved_by: "fixture operator", approved_call_cap: 42, approved_maximum_usd: plan.estimate.maximum_usd, authorization: "execute-exact-plan-once" };
  return buildEvidence({ run: { id: "fixture-run", started_at: at(0), ended_at: at(1000), call_cap: CALL_CAP, calls_made: records.length }, plan, input, records, adapter: { endpoint: "http://127.0.0.1:8789/", expected_health: expectedHealth(sources, runtime), observed_health: expectedHealth(sources, runtime), identity_match: true }, approval, pricing: plan.estimate });
}

test("the declared direct-output fixture catalog executes through the authoritative classifier", async () => { const result = await executeFixtures(); assert.equal(result.passed, true); assert.equal(result.passing_ids.length, 13); });
test("request identities bind role, resolved model, prompt, schema, parameters, and exact input", () => { const request = buildRequest(ROLE_IDENTITIES[0], fixtureInput()); assert.equal(request.role, "primary"); assert.equal(request.body.model, ROLE_IDENTITIES[0].resolved_model); assert.match(request.request_sha256, /^[a-f0-9]{64}$/); assert.notEqual(request.request_sha256, buildRequest(ROLE_IDENTITIES[1], fixtureInput()).request_sha256); });
test("classification accepts direct Candidates and rejects text, wrappers, ambiguity, repair, errors, and timeout", () => { assert.equal(classifyCall({ call_state: "received", output: fixtureCandidate() }).classification, "direct_valid"); for (const output of [JSON.stringify(fixtureCandidate()), { candidate: fixtureCandidate() }, [fixtureCandidate(), fixtureCandidate()], ` \n${fixtureCandidate().title}`]) assert.equal(classifyCall({ call_state: "received", output }).classification, "invalid_output"); assert.equal(classifyCall({ call_state: "provider_error" }).classification, "provider_error"); assert.equal(classifyCall({ call_state: "timeout" }).classification, "timeout"); });
test("schedule is sequential, zero retry/replacement, and bounded to 42 calls", async () => { let active = 0; let maximum = 0; let calls = 0; const records = await executeSchedule(ROLE_IDENTITIES.map((role) => buildRequest(role, fixtureInput())), async () => { calls += 1; active += 1; maximum = Math.max(maximum, active); active -= 1; return { started_at: at(calls * 2), ended_at: at(calls * 2 + 1), latency_ms: 1, call_state: "received", output: fixtureCandidate(), usage: null }; }); assert.equal(calls, 42); assert.equal(records.length, 42); assert.equal(maximum, 1); });
test("a failed probe prevents trials only for its own role", async () => { let calls = 0; const records = await executeSchedule(ROLE_IDENTITIES.map((role) => buildRequest(role, fixtureInput())), async (request) => { calls += 1; return { started_at: at(calls * 2), ended_at: at(calls * 2 + 1), latency_ms: 1, call_state: request.role === "primary" ? "provider_error" : "received", output: request.role === "primary" ? null : fixtureCandidate(), usage: null }; }); assert.equal(records.filter(({ role }) => role === "primary").length, 1); assert.equal(records.filter(({ role }) => role === "fallback").length, 21); });
test("plans are deterministic, source-bound, cost-bounded, and approvals are exact and fresh", async () => { const created = at(0); const plan = await createPlan({ approval_run_id: "test-plan", created_at: created, input: fixtureInput(), authority: { account_profile: "reviewed", credential_path: "wrangler-remote-binding", headroom_confirmed: true } }); assert.equal(plan.call_cap, 42); const approval = { schema_version: APPROVAL_VERSION, plan_ref: plan.plan_ref, approval_run_id: plan.approval_run_id, approved_at: at(100), approved_by: "operator", approved_call_cap: 42, approved_maximum_usd: plan.estimate.maximum_usd, authorization: "execute-exact-plan-once" }; assert.equal(validateApproval(approval, plan, Date.parse(at(200))).valid, true); assert.equal(validateApproval({ ...approval, plan_ref: "0".repeat(64) }, plan, Date.parse(at(200))).valid, false); });
test("independent verifier accepts recomputable evidence and derives independent manifests", async () => { const evidence = await validEvidence(); const result = await verifyEvidence(evidence); assert.equal(result.valid, true, result.errors.join("\n")); assert.equal(evidence.outcome.by_role.primary.decision, "GO"); assert.equal(evidence.outcome.by_role.fallback.decision, "GO"); const qualification = deriveManifests(evidence, result.predicate_results); assert.notEqual(qualification.qualification_refs.primary, qualification.qualification_refs.fallback); });
test("a role below 19-of-20 is NO-GO without changing the other role", async () => { const evidence = await validEvidence({ primaryFailures: 2 }); const result = await verifyEvidence(evidence); assert.equal(result.valid, true, result.errors.join("\n")); assert.equal(evidence.outcome.by_role.primary.decision, "NO-GO"); assert.equal(evidence.outcome.by_role.fallback.decision, "GO"); const qualification = deriveManifests(evidence, result.predicate_results); assert.equal(qualification.manifests.primary.decision, "NO-GO"); assert.equal(qualification.manifests.fallback.decision, "GO"); assert.notEqual(qualification.qualification_refs.primary, qualification.qualification_refs.fallback); });
test("live execution refuses CI and non-interactive use before reading plan bytes", () => { const result = spawnSync(process.execPath, ["spikes/generation-qualification/run.mjs", "live", "does-not-exist.plan.json", "does-not-exist.approval.json"], { cwd: process.cwd(), env: { ...process.env, CI: "1" }, encoding: "utf8" }); assert.notEqual(result.status, 0); assert.match(result.stderr, /requires an interactive TTY and refuses CI/); assert.doesNotMatch(result.stderr, /ENOENT/); });
test("public verifier accepts external bytes without runner mocks", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-evidence-")); const file = path.join(directory, "external.json"); const evidence = await validEvidence(); await writeFile(file, `${JSON.stringify(evidence, null, 2)}\n`); const result = await verifyBytes(await readFile(file)); assert.equal(result.valid, true, result.errors.join("\n")); });
test("tampering retained identities and predicates fails closed", async () => { const mutations = [
  (e) => { e.sources[0].sha256 = "0".repeat(64); }, (e) => { e.runtime.runtime_identity_sha256 = "0".repeat(64); },
  (e) => { e.requests[0].request_sha256 = "0".repeat(64); }, (e) => { e.adapter.identity_match = false; },
  (e) => { e.records[0].candidate_ref = "0".repeat(64); }, (e) => { e.summary.by_role.primary.direct_valid -= 1; },
  (e) => { e.outcome.by_role.primary.decision = "NO-GO"; }, (e) => { e.report += "tamper"; },
  (e) => { e.oracle.hash = "0".repeat(64); }, (e) => { e.predicate_results[0].pass = false; },
  ]; for (const mutate of mutations) { const evidence = await validEvidence(); mutate(evidence); const result = await verifyEvidence(evidence); assert.equal(result.valid, false); } });
test("public verifier contains invalid times and rejects plan, approval, health, record, cost, run, index, and overlap mutations", async () => { const mutations = [
  (e) => { e.run.started_at = "not-a-time"; }, (e) => { e.plan.created_at = "not-a-time"; }, (e) => { e.plan.plan_ref = "0".repeat(64); },
  (e) => { e.plan.roles = [{ ...e.plan.roles[0], resolved_model: "drift" }, e.plan.roles[1]]; }, (e) => { e.approval.approved_maximum_usd += 1; }, (e) => { e.approval.approved_at = at(-1); },
  (e) => { e.adapter.observed_health.ok = false; }, (e) => { e.adapter.endpoint = "https://example.com/"; },
  (e) => { e.records[0].retained_sha256 = "0".repeat(64); }, (e) => { e.records[0].retained_bytes += 1; },
  (e) => { e.records[0].usage = { input_tokens: 1, output_tokens: 1, total_tokens: 2 }; }, (e) => { e.records[0].cost_usd += 1; },
  (e) => { e.run.calls_made -= 1; }, (e) => { e.run.call_cap = 41; }, (e) => { e.run.id = "bad id"; },
  (e) => { e.records[0].index = 2; }, (e) => { e.records[1].started_at = e.records[0].started_at; },
  ]; for (const mutate of mutations) { const evidence = await validEvidence(); mutate(evidence); const result = await verifyBytes(Buffer.from(JSON.stringify(evidence))); assert.equal(result.valid, false); } });
test("oversized output retains bounded verifiable metadata without the unbounded value", async () => { const evidence = await validEvidence(); const request = evidence.requests[0]; const oversized = retained("trial", 1, request, { call_state: "received", output: { ...fixtureCandidate(), title: "x".repeat(70000) } }, 4); evidence.records[1] = oversized; const rebuilt = await buildEvidence({ run: evidence.run, plan: evidence.plan, input: evidence.input, records: evidence.records, adapter: evidence.adapter, approval: evidence.approval, pricing: evidence.pricing }); assert.equal(rebuilt.records[1].retained, null); assert.ok(rebuilt.records[1].retained_bytes > 65536); const result = await verifyEvidence(rebuilt); assert.equal(result.valid, true, result.errors.join("\n")); });
test("response schema and fixture catalog are closed at every boundary", async () => { assert.equal(CANDIDATE_RESPONSE_FORMAT.json_schema.properties.before_after.additionalProperties, false); assert.equal(CANDIDATE_RESPONSE_FORMAT.json_schema.properties.change_level.additionalProperties, false); assert.equal(CANDIDATE_RESPONSE_FORMAT.json_schema.properties.stays_same.additionalProperties, false); const document = JSON.parse(await readFile(new URL("./fixtures.json", import.meta.url), "utf8")); assert.equal((await executeFixtures({ ...document, schema_version: "drift" })).passed, false); assert.equal((await executeFixtures({ ...document, cases: [{ ...document.cases[0], extra: true }] })).passed, false); assert.equal((await executeFixtures({ ...document, cases: [{ ...document.cases[0], shape: "unknown" }] })).passed, false); });
test("publication failure rolls back every member and completed receipts retain calls and actual spend", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-publication-")); const members = { "set.evidence.json": Buffer.from("evidence"), "set.report.md": Buffer.from("report"), "set.qualification.json": Buffer.from("qualification") }; await assert.rejects(() => publishArtifactSet(directory, "set", members, { beforeMarker() { throw new Error("marker failure"); } })); assert.deepEqual(await readdir(directory), []); const marker = await publishArtifactSet(directory, "set", members); const receiptPath = path.join(directory, "receipt.json"); const receipt = { schema_version: "oddspark.generation-spend-receipt/v1", state: "reserved-before-inference" }; await writeFile(receiptPath, JSON.stringify(receipt)); const records = [{ cost_usd: 0.1 }, { cost_usd: 0.2 }]; const completed = await completeSpendReceipt(receiptPath, receipt, records, marker, at(1000)); assert.equal(completed.state, "completed"); assert.equal(completed.calls_made, 2); assert.equal(completed.actual_spend_usd, 0.30000000000000004); assert.equal(JSON.parse(await readFile(receiptPath, "utf8")).completion_marker, "set.complete.json"); });
test("every closed predicate is retained exactly once", async () => { const evidence = await validEvidence(); assert.deepEqual(evidence.predicate_results.map(({ id }) => id), GENERATION_PREDICATES); assert.equal(new Set(GENERATION_PREDICATES).size, GENERATION_PREDICATES.length); });
