import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, readdir, rename, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { APPROVAL_VERSION, costForUsage, createPlan, deriveManifests, validateApproval } from "./qualification.mjs";
import { CALL_CAP, CANDIDATE_RESPONSE_FORMAT, GENERATION_PREDICATES, ROLE_IDENTITIES, buildRequest, classifyCall, fixtureCandidate, fixtureInput } from "./contract.mjs";
import { executeFixtures } from "./fixture-executor.mjs";
import { buildEvidence, expectedHealth, runtimeIdentity, sourceIdentity, verifyEvidence } from "./evidence-v2.mjs";
import { STALE_LOCK_AGE_MS, acquireCycleLock, atomic, completeSpendReceipt, executeSchedule, publishArtifactSet, releaseCycleLock, terminalizeFailure, verifyPublishedArtifactSet } from "./run.mjs";
import { verifyBytes } from "./verify-v2.mjs";
import adapterWorker, { decodeStructuredResponse } from "./worker.mjs";
import { findPriorOperationalRecovery, readStableNoFollow, receiptValid } from "./recovery-finder.mjs";
import { startAdapter } from "./start-adapter.mjs";

const at = (offset) => new Date(Date.parse("2026-08-18T20:00:00.000Z") + offset).toISOString();
function retained(kind, index, request, call, offset) { const result = classifyCall(call); const usage = { input_tokens: 1, output_tokens: 1 }; return { kind, role: request.role, resolved_model: request.resolved_model, index, started_at: at(offset), ended_at: at(offset + 1), latency_ms: 1, call_state: call.call_state, classification: result.classification, candidate: result.candidate, candidate_ref: result.candidate_ref, issues: result.issues, retained: result.retained, retained_sha256: result.retained_sha256, retained_bytes: result.retained_bytes, usage, cost_usd: costForUsage(request.resolved_model, usage), request_sha256: request.request_sha256 }; }
async function validEvidence({ primaryFailures = 0, approvalRunId = "test", runId = "fixture-run" } = {}) {
  const input = fixtureInput(); const requests = ROLE_IDENTITIES.map((role) => buildRequest(role, input)); const records = []; let offset = 0;
  for (const request of requests) records.push(retained("probe", 1, request, { call_state: "received", output: fixtureCandidate() }, offset += 2));
  for (const request of requests) for (let index = 1; index <= 20; index += 1) { const failed = request.role === "primary" && index <= primaryFailures; records.push(retained("trial", index, request, failed ? { call_state: "provider_error" } : { call_state: "received", output: fixtureCandidate() }, offset += 2)); }
  const sources = await sourceIdentity(); const runtime = await runtimeIdentity(); const plan = await createPlan({ approval_run_id: approvalRunId, created_at: at(0), input, authority: { account_profile: "fixture", credential_path: "wrangler-remote-binding", headroom_confirmed: true } }); const approval = { schema_version: APPROVAL_VERSION, plan_ref: plan.plan_ref, approval_run_id: approvalRunId, approved_at: at(0), approved_by: "fixture operator", approved_call_cap: 42, approved_maximum_usd: plan.estimate.maximum_usd, authorization: "execute-exact-plan-once" };
  return buildEvidence({ run: { id: runId, started_at: at(0), ended_at: at(1000), call_cap: CALL_CAP, calls_made: records.length }, plan, input, records, adapter: { endpoint: "http://127.0.0.1:8789/", expected_health: expectedHealth(sources, runtime), observed_health: expectedHealth(sources, runtime), identity_match: true }, approval, pricing: plan.estimate });
}

test("the declared direct-output fixture catalog executes through the authoritative classifier", async () => { const result = await executeFixtures(); assert.equal(result.passed, true); assert.equal(result.passing_ids.length, 13); });
test("request identities bind role, resolved model, prompt, schema, parameters, and exact input", () => { const request = buildRequest(ROLE_IDENTITIES[0], fixtureInput()); assert.equal(request.role, "primary"); assert.equal(request.body.model, ROLE_IDENTITIES[0].resolved_model); assert.match(request.request_sha256, /^[a-f0-9]{64}$/); assert.notEqual(request.request_sha256, buildRequest(ROLE_IDENTITIES[1], fixtureInput()).request_sha256); });
test("classification accepts direct Candidates and rejects text, wrappers, ambiguity, repair, errors, and timeout", () => { assert.equal(classifyCall({ call_state: "received", output: fixtureCandidate() }).classification, "direct_valid"); for (const output of [JSON.stringify(fixtureCandidate()), { candidate: fixtureCandidate() }, [fixtureCandidate(), fixtureCandidate()], ` \n${fixtureCandidate().title}`]) assert.equal(classifyCall({ call_state: "received", output }).classification, "invalid_output"); assert.equal(classifyCall({ call_state: "provider_error" }).classification, "provider_error"); assert.equal(classifyCall({ call_state: "timeout" }).classification, "timeout"); });
test("adapter decodes exactly one complete structured transport value without repair or coercion", () => {
  const candidate = fixtureCandidate();
  assert.deepEqual(decodeStructuredResponse({ choices: [{ index: 0, message: { role: "assistant", content: JSON.stringify(candidate) } }], usage: {} }), candidate);
  const rejected = [
    null,
    candidate,
    { response: candidate },
    { choices: [] },
    { choices: [{ index: 0, message: { content: JSON.stringify(candidate) } }, { index: 1, message: { content: JSON.stringify(candidate) } }] },
    { choices: [{ index: 1, message: { content: JSON.stringify(candidate) } }] },
    { choices: [{ index: 0, message: { content: candidate } }] },
    { choices: [{ index: 0, message: { content: `Here is the result: ${JSON.stringify(candidate)}` } }] },
    { choices: [{ index: 0, message: { content: `\`\`\`json\n${JSON.stringify(candidate)}\n\`\`\`` } }] },
    { choices: [{ index: 0, message: { content: `${JSON.stringify(candidate)} trailing` } }] },
    { choices: [{ index: 0, message: { content: JSON.stringify([candidate]) } }] },
    { choices: [{ index: 0, message: { content: JSON.stringify("structured-looking text") } }] },
  ];
  for (const value of rejected) assert.throws(() => decodeStructuredResponse(value));
  assert.equal(classifyCall({ call_state: "received", output: decodeStructuredResponse({ choices: [{ index: 0, message: { content: JSON.stringify({ ...candidate, extra: true }) } }] }) }).classification, "invalid_output");
});
test("schedule is sequential, zero retry/replacement, and bounded to 42 calls", async () => { let active = 0; let maximum = 0; let calls = 0; const records = await executeSchedule(ROLE_IDENTITIES.map((role) => buildRequest(role, fixtureInput())), async () => { calls += 1; active += 1; maximum = Math.max(maximum, active); active -= 1; return { started_at: at(calls * 2), ended_at: at(calls * 2 + 1), latency_ms: 1, call_state: "received", output: fixtureCandidate(), usage: null }; }); assert.equal(calls, 42); assert.equal(records.length, 42); assert.equal(maximum, 1); });
test("a failed probe prevents trials only for its own role", async () => { let calls = 0; const records = await executeSchedule(ROLE_IDENTITIES.map((role) => buildRequest(role, fixtureInput())), async (request) => { calls += 1; return { started_at: at(calls * 2), ended_at: at(calls * 2 + 1), latency_ms: 1, call_state: request.role === "primary" ? "provider_error" : "received", output: request.role === "primary" ? null : fixtureCandidate(), usage: null }; }); assert.equal(records.filter(({ role }) => role === "primary").length, 1); assert.equal(records.filter(({ role }) => role === "fallback").length, 21); });
test("plans are deterministic, source-bound, cost-bounded, and approvals are exact and fresh", async () => { const created = at(0); const plan = await createPlan({ approval_run_id: "test-plan", created_at: created, input: fixtureInput(), authority: { account_profile: "reviewed", credential_path: "wrangler-remote-binding", headroom_confirmed: true } }); assert.equal(plan.call_cap, 42); const approval = { schema_version: APPROVAL_VERSION, plan_ref: plan.plan_ref, approval_run_id: plan.approval_run_id, approved_at: at(100), approved_by: "operator", approved_call_cap: 42, approved_maximum_usd: plan.estimate.maximum_usd, authorization: "execute-exact-plan-once" }; assert.equal(validateApproval(approval, plan, Date.parse(at(200))).valid, true); assert.equal(validateApproval({ ...approval, plan_ref: "0".repeat(64) }, plan, Date.parse(at(200))).valid, false); });
test("independent verifier accepts recomputable evidence and derives independent manifests", async () => { const evidence = await validEvidence(); const result = await verifyEvidence(evidence); assert.equal(result.valid, true, result.errors.join("\n")); assert.equal(evidence.outcome.by_role.primary.decision, "GO"); assert.equal(evidence.outcome.by_role.fallback.decision, "GO"); const qualification = await deriveManifests(evidence); assert.notEqual(qualification.qualification_refs.primary, qualification.qualification_refs.fallback); });
test("a role below 19-of-20 is NO-GO without changing the other role", async () => { const evidence = await validEvidence({ primaryFailures: 2 }); const result = await verifyEvidence(evidence); assert.equal(result.valid, true, result.errors.join("\n")); assert.equal(evidence.outcome.by_role.primary.decision, "NO-GO"); assert.equal(evidence.outcome.by_role.fallback.decision, "GO"); const qualification = await deriveManifests(evidence); assert.equal(qualification.manifests.primary.decision, "NO-GO"); assert.equal(qualification.manifests.fallback.decision, "GO"); assert.equal(qualification.qualification_refs.primary, null); assert.match(qualification.qualification_refs.fallback, /^[a-f0-9]{64}$/); assert.deepEqual(qualification.role_qualification_set.ordered_members.map(({ role }) => role), ["fallback"]); });
test("live execution refuses CI and non-interactive use before reading plan bytes", () => { const result = spawnSync(process.execPath, ["spikes/generation-qualification/run.mjs", "live", "does-not-exist.plan.json", "does-not-exist.approval.json"], { cwd: process.cwd(), env: { ...process.env, CI: "1" }, encoding: "utf8" }); assert.notEqual(result.status, 0); assert.match(result.stderr, /requires an interactive TTY and refuses CI/); assert.doesNotMatch(result.stderr, /ENOENT/); });
test("adapter launcher refuses to spawn without exact plan and approval paths", () => { const result = spawnSync(process.execPath, ["spikes/generation-qualification/start-adapter.mjs"], { cwd: process.cwd(), encoding: "utf8" }); assert.notEqual(result.status, 0); assert.match(result.stderr, /Usage: start-adapter/); assert.doesNotMatch(result.stderr, /wrangler/); });
test("adapter launcher validates exact authority, reaches only an injected spawn, and schedules expiry", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-launcher-")); const now = Date.now(); const plan = await createPlan({ approval_run_id: "launcher-test", created_at: new Date(now - 1000).toISOString(), input: fixtureInput(), authority: { account_profile: "fixture", credential_path: "wrangler-remote-binding", headroom_confirmed: true } }); const approval = { schema_version: APPROVAL_VERSION, plan_ref: plan.plan_ref, approval_run_id: plan.approval_run_id, approved_at: new Date(now).toISOString(), approved_by: "operator", approved_call_cap: CALL_CAP, approved_maximum_usd: plan.estimate.maximum_usd, authorization: "execute-exact-plan-once" }; const planFile = path.join(directory, "plan.json"); const approvalFile = path.join(directory, "approval.json"); await writeFile(planFile, JSON.stringify(plan)); await writeFile(approvalFile, JSON.stringify(approval)); let spawned = 0; let delay = 0; const child = { kill() {}, on() {} }; const result = await startAdapter(planFile, approvalFile, { now, findRecovery: async () => ({ state: "available", allowance_consumed: false }), spawn: () => { spawned += 1; return child; }, setTimeout: (_fn, ms) => { delay = ms; return { unref() {} }; }, attachProcessHandlers: false }); assert.equal(spawned, 1); assert.equal(result.child, child); assert.equal(delay, 4 * 60 * 60 * 1000); });
test("plan CLI writes only an unapproved null-execution bundle outside operational results", async () => { const id = `plan-test-${process.pid}`; const result = spawnSync(process.execPath, ["spikes/generation-qualification/run.mjs", "plan", id], { cwd: process.cwd(), encoding: "utf8" }); assert.equal(result.status, 0, result.stderr); const directory = result.stdout.trim(); assert.equal(path.dirname(directory), os.tmpdir()); assert.deepEqual((await readdir(directory)).sort(), [`${id}.approval-template.json`, `${id}.execution.json`, `${id}.plan.json`]); const approval = JSON.parse(await readFile(path.join(directory, `${id}.approval-template.json`), "utf8")); const execution = JSON.parse(await readFile(path.join(directory, `${id}.execution.json`), "utf8")); assert.equal(approval.approved_at, null); assert.equal(approval.authorization, null); assert.equal(execution.approval, null); assert.equal(execution.execution, null); assert.equal(execution.allowance_consumed, false); assert.equal(directory.startsWith(path.resolve("spikes/generation-qualification/results")), false); });
test("public verifier accepts external bytes without runner mocks", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-evidence-")); const file = path.join(directory, "external.json"); const evidence = await validEvidence(); await writeFile(file, `${JSON.stringify(evidence, null, 2)}\n`); const result = await verifyBytes(await readFile(file)); assert.equal(result.valid, true, result.errors.join("\n")); });
test("tampering retained identities and predicates fails closed", async () => { const mutations = [
  (e) => { e.sources[0].sha256 = "0".repeat(64); }, (e) => { e.runtime.runtime_identity_sha256 = "0".repeat(64); },
  (e) => { e.requests[0].request_sha256 = "0".repeat(64); }, (e) => { e.adapter.identity_match = false; },
  (e) => { e.records[0].candidate_ref = "0".repeat(64); }, (e) => { e.summary.by_role.primary.direct_valid -= 1; },
  (e) => { e.outcome.by_role.primary.decision = "NO-GO"; }, (e) => { e.report += "tamper"; },
  (e) => { e.oracle.hash = "0".repeat(64); }, (e) => { e.predicate_results[0].pass = false; },
  ]; for (const mutate of mutations) { const evidence = await validEvidence(); mutate(evidence); const result = await verifyEvidence(evidence); assert.equal(result.valid, false); } });
test("public verifier contains invalid times and rejects plan, approval, health, record, cost, run, index, and overlap mutations", async () => { const mutations = [
  (e) => { e.run.started_at = "not-a-time"; }, (e) => { e.plan.created_at = "not-a-time"; }, (e) => { e.plan.plan_ref = "0".repeat(64); },
  (e) => { e.plan.roles = [{ ...e.plan.roles[0], resolved_model: "drift" }, e.plan.roles[1]]; }, (e) => { e.approval.approved_maximum_usd += 1; }, (e) => { e.approval.approved_at = at(-1); },
  (e) => { e.adapter.observed_health.ok = false; }, (e) => { e.adapter.endpoint = "https://example.com/"; },
  (e) => { e.records[0].retained_sha256 = "0".repeat(64); }, (e) => { e.records[0].retained_bytes += 1; },
  (e) => { e.records[0].usage = { input_tokens: 1, output_tokens: 1, total_tokens: 2 }; }, (e) => { e.records[0].cost_usd += 1; },
  (e) => { e.run.calls_made -= 1; }, (e) => { e.run.call_cap = 41; }, (e) => { e.run.id = "bad id"; },
  (e) => { e.records[0].index = 2; }, (e) => { e.records[1].started_at = e.records[0].started_at; },
  ]; for (const mutate of mutations) { const evidence = await validEvidence(); mutate(evidence); const result = await verifyBytes(Buffer.from(JSON.stringify(evidence))); assert.equal(result.valid, false); } });
test("oversized output retains bounded verifiable metadata without the unbounded value", async () => { const evidence = await validEvidence(); const request = evidence.requests[0]; const oversized = retained("trial", 1, request, { call_state: "received", output: { ...fixtureCandidate(), title: "x".repeat(70000) } }, 6); evidence.records[2] = oversized; const rebuilt = await buildEvidence({ run: evidence.run, plan: evidence.plan, input: evidence.input, records: evidence.records, adapter: evidence.adapter, approval: evidence.approval, pricing: evidence.pricing }); assert.equal(rebuilt.records[2].retained, null); assert.ok(rebuilt.records[2].retained_bytes > 65536); const result = await verifyEvidence(rebuilt); assert.equal(result.valid, true, result.errors.join("\n")); });
test("response schema and fixture catalog are closed at every boundary", async () => { assert.equal(CANDIDATE_RESPONSE_FORMAT.json_schema.properties.before_after.additionalProperties, false); assert.equal(CANDIDATE_RESPONSE_FORMAT.json_schema.properties.change_level.additionalProperties, false); assert.equal(CANDIDATE_RESPONSE_FORMAT.json_schema.properties.stays_same.additionalProperties, false); const document = JSON.parse(await readFile(new URL("./fixtures.json", import.meta.url), "utf8")); assert.equal((await executeFixtures({ ...document, schema_version: "drift" })).passed, false); assert.equal((await executeFixtures({ ...document, cases: [{ ...document.cases[0], extra: true }] })).passed, false); assert.equal((await executeFixtures({ ...document, cases: [{ ...document.cases[0], shape: "unknown" }] })).passed, false); });
test("publication failure rolls back every member and completed receipts retain calls and actual spend", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-publication-")); const members = { "set.evidence.json": Buffer.from("evidence"), "set.report.md": Buffer.from("report"), "set.qualification.json": Buffer.from("qualification") }; await assert.rejects(() => publishArtifactSet(directory, "set", members, { beforeMarker() { throw new Error("marker failure"); } })); assert.deepEqual(await readdir(directory), []); const marker = await publishArtifactSet(directory, "set", members); const receiptPath = path.join(directory, "receipt.json"); const receipt = { schema_version: "oddspark.generation-spend-receipt/v1", state: "reserved-before-inference" }; await writeFile(receiptPath, JSON.stringify(receipt)); const records = [{ cost_usd: 0.1 }, { cost_usd: 0.2 }]; const completed = await completeSpendReceipt(receiptPath, receipt, records, marker, at(1000)); assert.equal(completed.state, "completed-spent"); assert.equal(completed.calls_made, 2); assert.equal(completed.actual_spend_usd, 0.30000000000000004); assert.equal(JSON.parse(await readFile(receiptPath, "utf8")).completion_marker, "set.complete.json"); });
test("directory fsync failure removes a newly installed atomic file", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-fsync-")); const file = path.join(directory, "member.json"); await assert.rejects(atomic(file, Buffer.from("bytes"), { sync: async () => { throw new Error("fsync failed"); } }), /fsync failed/); assert.deepEqual(await readdir(directory), []); });
test("terminalization double failure preserves both errors", async () => { const original = new Error("verification failed"); await assert.rejects(terminalizeFailure("receipt", { plan_ref: "x" }, 1, original, async () => { throw new Error("disk failed"); }), (error) => error instanceof AggregateError && error.errors[0] === original && error.errors[1].message === "disk failed"); });
test("cycle lock is exclusive and never deletes a replacement inode", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-lock-")); const acquired = await acquireCycleLock(directory, { approval_run_id: "test" }); await assert.rejects(() => acquireCycleLock(directory), { code: "EEXIST" }); const successor = path.join(directory, "successor"); await writeFile(successor, "successor"); await rename(successor, acquired.lockPath); await assert.rejects(() => releaseCycleLock(acquired), /refusing to release successor/); assert.equal(await readFile(acquired.lockPath, "utf8"), "successor"); });
test("stale lock recovery requires the same owner, a dead pid, and age beyond the closed threshold", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-stale-lock-")); const acquired = await acquireCycleLock(directory); const lock = JSON.parse(await readFile(acquired.lockPath, "utf8")); lock.pid = 99999999; lock.acquired_at = new Date(Date.now() - STALE_LOCK_AGE_MS - 1).toISOString(); await writeFile(acquired.lockPath, `${JSON.stringify(lock)}\n`); const recovered = await acquireCycleLock(directory, {}, { recoverStale: true, alive: () => false }); assert.notEqual(recovered.nonce, acquired.nonce); await assert.rejects(releaseCycleLock(acquired), /refusing to release successor|nonce changed/); await releaseCycleLock(recovered); const live = await acquireCycleLock(directory); await assert.rejects(acquireCycleLock(directory, {}, { recoverStale: true, alive: () => true }), /live or not old enough/); await releaseCycleLock(live); });
test("published artifacts are re-opened and semantic failure removes the whole set", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-reread-")); const members = { "set.evidence.json": Buffer.from("{}\n"), "set.report.md": Buffer.from("report"), "set.qualification.json": Buffer.from("{}\n") }; await assert.rejects(() => publishArtifactSet(directory, "set", members, { semanticVerify: async () => ({ valid: false, errors: ["qualification mismatch"] }) }), /semantic verification failed/); assert.deepEqual(await readdir(directory), []); await publishArtifactSet(directory, "set", members); const verified = await verifyPublishedArtifactSet(directory, "set", members, async (reread) => ({ valid: reread["set.report.md"].toString() === "report", errors: [] })); assert.equal(verified.verification.valid, true); });
test("every closed predicate is retained exactly once", async () => { const evidence = await validEvidence(); assert.deepEqual(evidence.predicate_results.map(({ id }) => id), GENERATION_PREDICATES); assert.equal(new Set(GENERATION_PREDICATES).size, GENERATION_PREDICATES.length); });
test("receipt states have exact closed state-specific keys", () => { const attempt = "9d28e742-09bf-4f45-889f-7100c26db134"; const match = { groups: { run: "cycle", attempt } }; const common = { schema_version: "oddspark.generation-spend-receipt/v1", plan_ref: "a".repeat(64), approval_sha256: "b".repeat(64), approval_run_id: "cycle", attempt_id: attempt, reserved_at: at(0), call_cap: CALL_CAP }; const fixtures = [{ ...common, calls_started: 0, state: "zero-call" }, { ...common, calls_started: 1, state: "calling", first_call_started_at: at(1) }, { ...common, calls_started: 1, state: "consumed_incomplete", first_call_started_at: at(1), failed_at: at(2), original_error: "failed" }, { ...common, calls_started: 1, state: "completed-spent", first_call_started_at: at(1), completed_at: at(2), calls_made: 1, actual_spend_usd: null, actual_spend_known: false, completion_marker: `cycle-${attempt}.complete.json` }]; for (const receipt of fixtures) { assert.equal(receiptValid(receipt, match), true, receipt.state); const missing = structuredClone(receipt); delete missing[Object.keys(missing).at(-1)]; assert.equal(receiptValid(missing, match), false, `${receipt.state} missing`); assert.equal(receiptValid({ ...receipt, unknown: true }, match), false, `${receipt.state} unknown`); } assert.equal(receiptValid({ ...fixtures[0], calls_started: 1 }, match), false); assert.equal(receiptValid({ ...fixtures[3], actual_spend_known: false, actual_spend_usd: 1 }, match), false); });
test("publication re-open rejects byte tampering in every marker member", async () => { for (const target of ["set.evidence.json", "set.report.md", "set.qualification.json"]) { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-member-tamper-")); const members = { "set.evidence.json": Buffer.from("evidence"), "set.report.md": Buffer.from("report--"), "set.qualification.json": Buffer.from("qualify-") }; await publishArtifactSet(directory, "set", members); await writeFile(path.join(directory, target), Buffer.alloc(members[target].length, 120)); await assert.rejects(verifyPublishedArtifactSet(directory, "set", members), /published member bytes drifted/); } });
test("qualification authority rejects unverified evidence and reordered global schedules", async () => { const evidence = await validEvidence(); [evidence.records[2], evidence.records[22]] = [evidence.records[22], evidence.records[2]]; const checked = await verifyEvidence(evidence); assert.equal(checked.valid, false); assert.match(checked.errors.join("; "), /global call schedule/); await assert.rejects(deriveManifests(evidence), /verified evidence is required/); });
test("fallback pricing is exact and recomputed in every evidence aggregate", async () => { const evidence = await validEvidence(); const fallback = evidence.summary.by_role.fallback; assert.equal(fallback.cost_known, true); const expected = evidence.records.filter((record) => record.role === "fallback" && record.kind === "trial").reduce((sum, record) => sum + record.cost_usd, 0); assert.equal(fallback.cost_usd, expected); });
test("recovery rejects malformed current-looking filenames", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-malformed-name-")); await writeFile(path.join(directory, "cycle-not-a-uuid.spend-receipt.json"), "{}"); await assert.rejects(findPriorOperationalRecovery(directory), /malformed current-looking artifact names/); });
test("loopback run requests require the exact launcher-bound authority", async () => { let calls = 0; const env = { AUTHORITY_SHA256: "a".repeat(64), PRIMARY_MODEL: ROLE_IDENTITIES[0].resolved_model, FALLBACK_MODEL: ROLE_IDENTITIES[1].resolved_model, AI: { run: async () => { calls += 1; return {}; } } }; const response = await adapterWorker.fetch(new Request("http://127.0.0.1/run", { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }), env); assert.equal(response.status, 403); assert.equal(calls, 0); });
test("recovery retains same-plan zero-call attempts and rejects renamed receipts", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-recovery-")); const attempt = "9d28e742-09bf-4f45-889f-7100c26db134"; const name = `cycle-${attempt}.spend-receipt.json`; const receipt = { schema_version: "oddspark.generation-spend-receipt/v1", plan_ref: "a".repeat(64), approval_sha256: "b".repeat(64), approval_run_id: "cycle", attempt_id: attempt, reserved_at: at(0), call_cap: CALL_CAP, calls_started: 0, state: "zero-call" }; await writeFile(path.join(directory, name), `${JSON.stringify(receipt)}\n`); assert.equal((await findPriorOperationalRecovery(directory)).state, "available"); await rename(path.join(directory, name), path.join(directory, `wrong-${attempt}.spend-receipt.json`)); await assert.rejects(findPriorOperationalRecovery(directory), /invalid receipt/); });
test("recovery rejects orphan current-cycle publication and detects same-inode rewrites", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-recovery-")); const target = path.join(directory, "target"); await writeFile(target, "bytes"); await assert.rejects(readStableNoFollow(target, { afterRead: async () => writeFile(target, "BYTES") }), /changed while read/); await writeFile(path.join(directory, "cycle-9d28e742-09bf-4f45-889f-7100c26db134.evidence.json"), "{}"); await assert.rejects(findPriorOperationalRecovery(directory), /orphan or conflicting/); });
test("zero-call history rejects cross-plan receipts and duplicate attempt identities", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-zero-history-")); const attempts = ["9d28e742-09bf-4f45-889f-7100c26db134", "29d28e74-209b-4f45-889f-7100c26db135"]; for (const [index, attempt] of attempts.entries()) { const receipt = { schema_version: "oddspark.generation-spend-receipt/v1", plan_ref: String(index).repeat(64), approval_sha256: "b".repeat(64), approval_run_id: "cycle", attempt_id: attempt, reserved_at: at(index), call_cap: CALL_CAP, calls_started: 0, state: "zero-call" }; await writeFile(path.join(directory, `cycle-${attempt}.spend-receipt.json`), JSON.stringify(receipt)); } await assert.rejects(findPriorOperationalRecovery(directory), /crosses plan\/run\/approval cycle/); const duplicate = { schema_version: "oddspark.generation-spend-receipt/v1", plan_ref: "a".repeat(64), approval_sha256: "b".repeat(64), approval_run_id: "other", attempt_id: attempts[0], reserved_at: at(0), call_cap: CALL_CAP, calls_started: 0, state: "zero-call" }; await writeFile(path.join(directory, `other-${attempts[0]}.spend-receipt.json`), JSON.stringify(duplicate)); await assert.rejects(findPriorOperationalRecovery(directory), /duplicates an attempt/); });
test("a verified completion cannot mask a conflicting current-cycle sibling", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-completed-conflict-")); const attempt = "9d28e742-09bf-4f45-889f-7100c26db134"; const evidence = await validEvidence({ approvalRunId: "cycle", runId: attempt }); const qualification = await deriveManifests(evidence); const base = `cycle-${attempt}`; const members = { [`${base}.evidence.json`]: Buffer.from(`${JSON.stringify(evidence, null, 2)}\n`), [`${base}.report.md`]: Buffer.from(evidence.report), [`${base}.qualification.json`]: Buffer.from(`${JSON.stringify(qualification, null, 2)}\n`) }; const marker = await publishArtifactSet(directory, base, members); const receiptPath = path.join(directory, `${base}.spend-receipt.json`); const receipt = { schema_version: "oddspark.generation-spend-receipt/v1", plan_ref: evidence.plan.plan_ref, approval_sha256: createHash("sha256").update(JSON.stringify(evidence.approval)).digest("hex"), approval_run_id: "cycle", attempt_id: attempt, reserved_at: at(0), call_cap: CALL_CAP, calls_started: evidence.records.length, first_call_started_at: evidence.records[0].started_at, state: "calling" }; await writeFile(receiptPath, JSON.stringify(receipt)); await completeSpendReceipt(receiptPath, receipt, evidence.records, marker, at(1000)); assert.equal((await findPriorOperationalRecovery(directory)).state, "completed"); await writeFile(path.join(directory, "conflict-29d28e74-209b-4f45-889f-7100c26db135.evidence.json"), "{}"); await assert.rejects(findPriorOperationalRecovery(directory), /orphan or conflicting/); });
test("legacy gpt-oss r2/r3 artifact sets are classified as history, not current-cycle orphans", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-legacy-history-")); const legacyNames = ["story-1-11-2026-08-19-r2.plan.json", "story-1-11-2026-08-19-r2.approval.json", "story-1-11-2026-08-19-r2.spend-receipt.json", "story-1-11-2026-08-19-r2-ead1cb17-38d7-41ce-8369-7fdc14098b29.complete.json", "story-1-11-2026-08-19-r2-ead1cb17-38d7-41ce-8369-7fdc14098b29.evidence.json", "story-1-11-2026-08-19-r2-ead1cb17-38d7-41ce-8369-7fdc14098b29.qualification.json", "story-1-11-2026-08-19-r2-ead1cb17-38d7-41ce-8369-7fdc14098b29.report.md", "story-1-11-2026-08-19-r3.plan.json", "story-1-11-2026-08-19-r3.approval.json", "story-1-11-2026-08-19-r3.spend-receipt.json", "story-1-11-2026-08-19-r3-f0da0590-4a83-4cf4-8401-6639af524959.complete.json", "story-1-11-2026-08-19-r3-f0da0590-4a83-4cf4-8401-6639af524959.evidence.json", "story-1-11-2026-08-19-r3-f0da0590-4a83-4cf4-8401-6639af524959.qualification.json", "story-1-11-2026-08-19-r3-f0da0590-4a83-4cf4-8401-6639af524959.report.md"]; for (const name of legacyNames) await writeFile(path.join(directory, name), "{}"); const attempt = "9d28e742-09bf-4f45-889f-7100c26db134"; const receipt = { schema_version: "oddspark.generation-spend-receipt/v1", plan_ref: "a".repeat(64), approval_sha256: "b".repeat(64), approval_run_id: "cycle", attempt_id: attempt, reserved_at: at(0), call_cap: CALL_CAP, calls_started: 0, state: "zero-call" }; await writeFile(path.join(directory, `cycle-${attempt}.spend-receipt.json`), JSON.stringify(receipt)); const found = await findPriorOperationalRecovery(directory); assert.equal(found.state, "available"); assert.equal(found.zero_call_attempts.length, 1); });
test("a completed prior cycle under drifted sources remains immutable history and does not block a new cycle", async () => { const directory = await mkdtemp(path.join(os.tmpdir(), "generation-prior-cycle-")); const l2names = ["story-1-11-2026-08-22-l2.plan.json", "story-1-11-2026-08-22-l2.approval.json", "story-1-11-2026-08-22-l2-57ef2429-0bac-48a9-9486-7cbc07dd32c7.spend-receipt.json", "story-1-11-2026-08-22-l2-57ef2429-0bac-48a9-9486-7cbc07dd32c7.complete.json", "story-1-11-2026-08-22-l2-57ef2429-0bac-48a9-9486-7cbc07dd32c7.evidence.json", "story-1-11-2026-08-22-l2-57ef2429-0bac-48a9-9486-7cbc07dd32c7.qualification.json", "story-1-11-2026-08-22-l2-57ef2429-0bac-48a9-9486-7cbc07dd32c7.report.md"]; for (const name of l2names) await writeFile(path.join(directory, name), "{}"); const attempt = "9d28e742-09bf-4f45-889f-7100c26db134"; const receipt = { schema_version: "oddspark.generation-spend-receipt/v1", plan_ref: "c".repeat(64), approval_sha256: "d".repeat(64), approval_run_id: "cycle", attempt_id: attempt, reserved_at: at(0), call_cap: CALL_CAP, calls_started: 0, state: "zero-call" }; await writeFile(path.join(directory, `cycle-${attempt}.spend-receipt.json`), JSON.stringify(receipt)); const found = await findPriorOperationalRecovery(directory); assert.equal(found.state, "available"); assert.equal(found.zero_call_attempts.length, 1); });
