#!/usr/bin/env node
// Executable form of the Story 1.2 I/O & Edge-Case Matrix.
// Dependency-free, same style as test.mjs: build throwaway fixture repos in a
// temp directory and drive the exported functions directly.

import assert from 'node:assert/strict';
import { execFileSync as run } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, copyFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  computeIdentity,
  verify,
  freeze,
  typesCheck,
  inspectDryRun,
  parseConfig,
  parseTomlValue,
  BASELINE_FILE,
} from './runtime-baseline.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

const ROOT_TOML = `name = "oddspark"
main = "src/worker.js"
compatibility_date = "2026-07-01"
compatibility_flags = ["global_fetch_strictly_public"]
preview_urls = true

[vars]
AI_MODEL = "m"

[ai]
binding = "AI"
remote = true

[[kv_namespaces]]
binding = "SPARKS"
id = "prod-id"

[[durable_objects.bindings]]
name = "METER"
class_name = "NeuronMeter"

[[routes]]
pattern = "oddspark.dev"
custom_domain = true

[observability]
enabled = true
`;

const OFFLINE_TOML = `name = "oddspark-offline"
main = "src/worker.js"
compatibility_date = "2026-07-01"
compatibility_flags = ["global_fetch_strictly_public"]
workers_dev = false
preview_urls = false

[vars]
AI_MODEL = "m"

[[kv_namespaces]]
binding = "SPARKS"
id = "oddspark-offline-local"

[[durable_objects.bindings]]
name = "METER"
class_name = "NeuronMeter"
`;

const SPIKE_TOML = `name = "oddspark-judge-fidelity-spike-local-only"
main = "worker.mjs"
compatibility_date = "2026-07-01"

[ai]
binding = "AI"
remote = true
`;
const GENERATION_SPIKE_TOML = `name = "oddspark-generation-llama-qualification-local-only"
main = "worker.mjs"
compatibility_date = "2026-07-01"

[ai]
binding = "AI"
remote = true
`;

const FILES = {
  'package.json': JSON.stringify({ engines: { node: '>=20' }, devDependencies: { wrangler: '4.123.0' } }, null, 2),
  'package-lock.json': JSON.stringify(
    {
      packages: {
        'node_modules/wrangler': { version: '4.123.0' },
        'node_modules/workerd': { version: '1.20260811.1' },
      },
    },
    null,
    2,
  ),
  'wrangler.toml': ROOT_TOML,
  'wrangler.offline.toml': OFFLINE_TOML,
  'spikes/judge-fidelity/wrangler.toml': SPIKE_TOML,
  'spikes/generation-qualification/wrangler.toml': GENERATION_SPIKE_TOML,
  'worker-configuration.d.ts':
    '// Generated by Wrangler by running `wrangler types`\n' +
    '// Runtime types generated with workerd@1.20260811.1 2026-07-01 global_fetch_strictly_public\n' +
    'interface Env {}\n',
};

const temps = [];

function makeRepo(overrides = {}) {
  const root = mkdtempSync(join(tmpdir(), 'oddspark-baseline-test-'));
  temps.push(root);
  for (const [rel, content] of Object.entries({ ...FILES, ...overrides })) {
    const path = join(root, rel);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
  // Fully hermetic: no signing, no hooks, no identity from the developer's
  // global config, and GIT_CEILING_DIRECTORIES so an outer repository (this one)
  // cannot be discovered if `git init` were ever to fail.
  const git = (...args) =>
    run('git', ['-c', 'commit.gpgsign=false', '-c', 'user.name=t', '-c', 'user.email=t@example.invalid', ...args], {
      cwd: root,
      stdio: 'pipe',
      env: { ...process.env, GIT_CEILING_DIRECTORIES: tmpdir(), GIT_CONFIG_GLOBAL: '/dev/null', GIT_CONFIG_SYSTEM: '/dev/null' },
    });
  git('init', '-q');
  git('add', '-A');
  git('commit', '-qm', 'fixture', '--no-verify');
  return root;
}

/** Fixture repo with a frozen baseline already in place. */
function frozenRepo(overrides = {}) {
  const root = makeRepo(overrides);
  freeze(root);
  return root;
}

const tests = [];
const test = (name, fn) => tests.push([name, fn]);

// --- Matrix row: verify, clean tree -----------------------------------------

test('verify passes on a clean frozen tree', () => {
  const result = verify(frozenRepo());
  assert.deepEqual(result.drift, []);
  assert.deepEqual(result.violations, []);
  assert.equal(result.ok, true);
  assert.match(result.identity.runtime_identity_sha256, /^[0-9a-f]{64}$/);
});

test('verify fails when the baseline file is absent', () => {
  const result = verify(makeRepo());
  assert.equal(result.ok, false);
  assert.match(result.violations.join(' '), /runtime-baseline\.json is missing/);
});

// --- Matrix row: verify, drift ----------------------------------------------

const driftCases = [
  ['wrangler lock version', {
    'package.json': JSON.stringify({ engines: { node: '>=20' }, devDependencies: { wrangler: '4.124.0' } }),
    'package-lock.json': JSON.stringify({
      packages: {
        'node_modules/wrangler': { version: '4.124.0' },
        'node_modules/workerd': { version: '1.20260811.1' },
      },
    }),
  }, /^wrangler$/],
  ['workerd lock version', {
    'package-lock.json': JSON.stringify({
      packages: {
        'node_modules/wrangler': { version: '4.123.0' },
        'node_modules/workerd': { version: '1.20260901.0' },
      },
    }),
  }, /^workerd$/],
  ['root wrangler.toml', { 'wrangler.toml': `${ROOT_TOML}\n# touched\n` }, /^configs\.root\.sha256$/],
  ['offline wrangler.toml', { 'wrangler.offline.toml': `${OFFLINE_TOML}\n# touched\n` }, /^configs\.offline\.sha256$/],
  ['spike wrangler.toml', { 'spikes/judge-fidelity/wrangler.toml': `${SPIKE_TOML}\n# touched\n` }, /^configs\.spike\.sha256$/],
  ['generation spike wrangler.toml', { 'spikes/generation-qualification/wrangler.toml': `${GENERATION_SPIKE_TOML}\n# touched\n` }, /^configs\.generation_spike\.sha256$/],
  ['worker-configuration.d.ts', { 'worker-configuration.d.ts': 'interface Env { X: string }\n' }, /^worker_types_sha256$/],
  ['compatibility date', { 'wrangler.toml': ROOT_TOML.replace('2026-07-01', '2026-08-04') }, /^compatibility_date$/],
  ['compatibility flags', {
    'wrangler.toml': ROOT_TOML.replace('["global_fetch_strictly_public"]', '["global_fetch_strictly_public", "nodejs_compat"]'),
  }, /^compatibility_flags$/],
];

for (const [label, overrides, field] of driftCases) {
  test(`verify reports drift in ${label}`, () => {
    const root = frozenRepo();
    for (const [rel, content] of Object.entries(overrides)) writeFileSync(join(root, rel), content);
    const result = verify(root);
    assert.equal(result.ok, false, `expected drift for ${label}`);
    const fields = result.drift.map((d) => d.field);
    assert.ok(fields.some((f) => field.test(f)), `expected a drift field matching ${field}, got ${fields.join(', ')}`);
    for (const item of result.drift) {
      assert.notEqual(item.expected, item.actual);
    }
  });
}

test('verify surfaces a wrangler pin that disagrees with the lockfile', () => {
  const root = frozenRepo();
  writeFileSync(
    join(root, 'package.json'),
    JSON.stringify({ engines: { node: '>=20' }, devDependencies: { wrangler: '4.124.0' } }),
  );
  const result = verify(root);
  assert.equal(result.ok, false);
  assert.match(result.violations.join(' '), /wrangler pin drift/);
});

// --- Matrix row: verify, isolation ------------------------------------------

const isolationCases = [
  ['offline config declaring [ai]', { 'wrangler.offline.toml': `${OFFLINE_TOML}\n[ai]\nbinding = "AI"\n` }, /\[ai\] binding/],
  ['offline config declaring remote = true', {
    'wrangler.offline.toml': OFFLINE_TOML.replace('id = "oddspark-offline-local"', 'id = "oddspark-offline-local"\nremote = true'),
  }, /remote = true/],
  ['spike config binding KV', {
    'spikes/judge-fidelity/wrangler.toml': `${SPIKE_TOML}\n[[kv_namespaces]]\nbinding = "SPARKS"\nid = "x"\n`,
  }, /kv_namespaces/],
  ['spike config binding a Durable Object', {
    'spikes/judge-fidelity/wrangler.toml': `${SPIKE_TOML}\n[[durable_objects.bindings]]\nname = "METER"\nclass_name = "NeuronMeter"\n`,
  }, /durable_objects/],
  ['spike config declaring routes', {
    'spikes/judge-fidelity/wrangler.toml': `${SPIKE_TOML}\n[[routes]]\npattern = "oddspark.dev"\n`,
  }, /routes/],
  ['spike config sharing the production Worker name', {
    'spikes/judge-fidelity/wrangler.toml': SPIKE_TOML.replace('oddspark-judge-fidelity-spike-local-only', 'oddspark'),
  }, /name must differ/],
  ['generation spike config binding KV', { 'spikes/generation-qualification/wrangler.toml': `${GENERATION_SPIKE_TOML}\n[[kv_namespaces]]\nbinding = "SPARKS"\nid = "x"\n` }, /generation spike config must not declare \[kv_namespaces\]/],
  ['generation spike config sharing the production Worker name', { 'spikes/generation-qualification/wrangler.toml': GENERATION_SPIKE_TOML.replace('oddspark-generation-llama-qualification-local-only', 'oddspark') }, /generation spike config name must differ from production/],
  ['generation spike config sharing the judge spike name', { 'spikes/generation-qualification/wrangler.toml': GENERATION_SPIKE_TOML.replace('oddspark-generation-llama-qualification-local-only', 'oddspark-judge-fidelity-spike-local-only') }, /generation spike config name must differ from judge spike/],
  ['generation spike config sharing the offline name', { 'spikes/generation-qualification/wrangler.toml': GENERATION_SPIKE_TOML.replace('oddspark-generation-llama-qualification-local-only', 'oddspark-offline') }, /generation spike config name must differ from offline/],
  ['offline config declaring an [env.*] section', {
    'wrangler.offline.toml': `${OFFLINE_TOML}\n[env.staging]\nname = "x"\n`,
  }, /offline config must not declare \[env\.\*\]/],
  ['spike config declaring an [env.*] section', {
    'spikes/judge-fidelity/wrangler.toml': `${SPIKE_TOML}\n[[env.live.routes]]\npattern = "x"\n`,
  }, /spike config must not declare \[env\.\*\]/],
  ['root config setting remote = true on KV', {
    'wrangler.toml': ROOT_TOML.replace('id = "prod-id"', 'id = "prod-id"\nremote = true'),
  }, /remote = true` on \[\[kv_namespaces\]\]/],
  ['root config without top-level preview_urls', {
    'wrangler.toml': ROOT_TOML.replace('preview_urls = true\n', ''),
  }, /must set top-level `preview_urls = true`/],
  ['offline config declaring ai via dotted keys', {
    'wrangler.offline.toml': OFFLINE_TOML.replace('\n[vars]', '\nai.binding = "AI"\nai.remote = true\n[vars]'),
  }, /\[ai\] binding/],
  ['spike config declaring a top-level route string', {
    'spikes/judge-fidelity/wrangler.toml': SPIKE_TOML.replace('main = "worker.mjs"\n', 'main = "worker.mjs"\nroute = "oddspark.dev/*"\n'),
  }, /routes/],
  ['spike config declaring a top-level routes array', {
    'spikes/judge-fidelity/wrangler.toml': SPIKE_TOML.replace('main = "worker.mjs"\n', 'main = "worker.mjs"\nroutes = ["oddspark.dev/*"]\n'),
  }, /routes/],
  ['a wrangler.jsonc shadowing the root config', { 'wrangler.jsonc': '{ "name": "oddspark" }\n' }, /wrangler\.jsonc must not exist/],
  ['root config with preview_urls buried in a section', {
    'wrangler.toml': ROOT_TOML.replace('preview_urls = true\n', '').replace('[observability]\nenabled = true', '[observability]\nenabled = true\npreview_urls = true'),
  }, /must set top-level `preview_urls = true`/],
];

for (const [label, overrides, pattern] of isolationCases) {
  test(`freeze refuses and verify fails on ${label}`, () => {
    // A violation introduced after a clean freeze must fail verification...
    const root = frozenRepo();
    for (const [rel, content] of Object.entries(overrides)) writeFileSync(join(root, rel), content);
    const result = verify(root);
    assert.equal(result.ok, false, `expected an isolation failure for ${label}`);
    assert.match(result.violations.join('\n'), pattern);
    // ...and must not be freezable into a new baseline either.
    assert.throws(() => freeze(root), /refusing to freeze a config that violates isolation/);
    assert.throws(() => freeze(root), pattern);
  });
}

// --- Matrix row: freeze ------------------------------------------------------

test('freeze writes deterministic, sorted, 2-space JSON with a trailing newline', () => {
  const root = makeRepo();
  const record = freeze(root);
  const text = readFileSync(join(root, BASELINE_FILE), 'utf8');
  assert.ok(text.endsWith('}\n'));
  assert.equal(text, `${JSON.stringify(JSON.parse(text), null, 2)}\n`);

  const keys = Object.keys(JSON.parse(text));
  assert.deepEqual(keys, [...keys].sort());

  const commit = run('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim();
  assert.equal(record.frozen_from_commit, commit);
  assert.equal(record.base_commit, commit);
  assert.match(record.source_state, /uncommitted worktree/);

  // Refreezing an unchanged tree changes nothing but the timestamp.
  const second = freeze(root);
  assert.equal(second.runtime_identity_sha256, record.runtime_identity_sha256);
  const stripped = (o) => JSON.stringify({ ...o, frozen_at: null });
  assert.equal(stripped(second), stripped(record));
});

test('freeze fails when a hashed file is missing', () => {
  const root = makeRepo();
  rmSync(join(root, 'worker-configuration.d.ts'));
  assert.throws(() => freeze(root), /missing required file: worker-configuration\.d\.ts/);
});

test('freeze fails outside a git repository', () => {
  const root = mkdtempSync(join(tmpdir(), 'oddspark-baseline-nogit-'));
  temps.push(root);
  for (const [rel, content] of Object.entries(FILES)) {
    const path = join(root, rel);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
  assert.throws(() => freeze(root), /could not read git HEAD/);
});

test('identity is stable across recomputation and covers the pinned toolchain', () => {
  const root = makeRepo();
  const a = computeIdentity(root);
  const b = computeIdentity(root);
  assert.deepEqual(a, b);
  assert.equal(a.wrangler, '4.123.0');
  assert.equal(a.workerd, '1.20260811.1');
  assert.equal(a.schema_version, 'oddspark.runtime-baseline/v1');
});

// --- Matrix row: types check -------------------------------------------------

test('types check passes on byte-identical output', () => {
  const root = makeRepo();
  const generated = join(root, 'generated.d.ts');
  writeFileSync(generated, FILES['worker-configuration.d.ts']);
  assert.deepEqual(typesCheck(root, generated), { ok: true });
});

const TYPES_LINES = FILES['worker-configuration.d.ts'].split('\n');

test('types check ignores only the wrangler provenance line', () => {
  const root = makeRepo();
  const generated = join(root, 'generated.d.ts');
  const lines = [...TYPES_LINES];
  lines[0] = '// Generated by Wrangler by running `wrangler types /tmp/x.d.ts` (hash: abc)';
  writeFileSync(generated, lines.join('\n'));
  assert.deepEqual(typesCheck(root, generated), { ok: true });
});

test('types check fails when the runtime-types header line differs', () => {
  const root = makeRepo();
  const generated = join(root, 'generated.d.ts');
  const lines = [...TYPES_LINES];
  lines[1] = '// Runtime types generated with workerd@1.20260901.0 2026-08-04 nodejs_compat';
  writeFileSync(generated, lines.join('\n'));
  const result = typesCheck(root, generated);
  assert.equal(result.ok, false, 'a different workerd/compat header must not be ignored');
  assert.match(result.reason, /differs from freshly generated types/);
});

test('types check fails when a binding differs', () => {
  const root = makeRepo();
  const generated = join(root, 'generated.d.ts');
  const lines = [...TYPES_LINES];
  lines[2] = 'interface Env { AI: Ai }';
  writeFileSync(generated, lines.join('\n'));
  const result = typesCheck(root, generated);
  assert.equal(result.ok, false);
  assert.match(result.reason, /differs from freshly generated types/);
});

test('types check fails when generated output is missing', () => {
  const root = makeRepo();
  const result = typesCheck(root, join(root, 'nope.d.ts'));
  assert.equal(result.ok, false);
  assert.match(result.reason, /generated types not found/);
});

// --- Parser ------------------------------------------------------------------

test('parser strips trailing comments outside quotes', () => {
  const parsed = parseConfig([
    'name = "oddspark" # the production Worker',
    'main = "src/worker.js"',
    'compatibility_flags = ["a", "b"] # reviewed',
    '[ai] # metered',
    'remote = true # dev only',
  ].join('\n'));
  assert.equal(parsed.flat.name, 'oddspark');
  assert.deepEqual(parsed.flat.compatibility_flags, ['a', 'b']);
  assert.deepEqual(parsed.sections, ['ai']);
  assert.deepEqual(parsed.remoteSections, ['ai']);
});

test('parser keeps a # that is inside a quoted string', () => {
  const parsed = parseConfig('name = "a#b"\n');
  assert.equal(parsed.flat.name, 'a#b');
});

test('parser supports single-quoted literal strings', () => {
  const parsed = parseConfig("name = 'oddspark'\nmain = 'src/worker.js'\n");
  assert.equal(parsed.flat.name, 'oddspark');
  assert.equal(parsed.flat.main, 'src/worker.js');
});

test('parser rejects a multi-line array', () => {
  assert.throws(() => parseConfig('compatibility_flags = [\n  "a",\n]\n'), /multi-line arrays are not supported/);
});

test('parser tolerates a multi-line array inside a section and still attributes remote', () => {
  const parsed = parseConfig(
    'name = "x"\n[[migrations]]\ntag = "v2"\nnew_sqlite_classes = [\n  "A",\n  "B",\n]\n[[kv_namespaces]]\nbinding = "K"\nremote = true\n',
  );
  assert.deepEqual(parsed.sections, ['kv_namespaces', 'migrations']);
  assert.deepEqual(parsed.remoteSections, ['kv_namespaces']);
});

test('parser rejects an unterminated string', () => {
  assert.throws(() => parseTomlValue('"oddspark'), /unterminated string/);
});

test('parser rejects an unparseable value rather than guessing', () => {
  assert.throws(() => parseTomlValue('2026-07-01'), /unparseable TOML/);
});

test('parser rejects duplicate top-level keys', () => {
  assert.throws(() => parseConfig('name = "a"\nname = "b"\n'), /duplicate top-level TOML key: name/);
});

test('parser records [env.*] headers as an env section', () => {
  const parsed = parseConfig('name = "x"\n[env.staging.ai]\nbinding = "AI"\nremote = true\n');
  assert.ok(parsed.sections.includes('env'), `expected an env section, got ${parsed.sections.join(', ')}`);
  assert.deepEqual(parsed.remoteSections, ['env']);
});

test('parser detects remote = true inside a top-level inline table', () => {
  const parsed = parseConfig('name = "x"\nai = { binding = "AI", remote = true }\n');
  assert.ok(parsed.sections.includes('ai'));
  assert.deepEqual(parsed.remoteSections, ['ai']);
  assert.equal(parsed.remote, true);
});

test('parser treats a top-level inline table as declaring its section without remote', () => {
  const parsed = parseConfig('name = "x"\nai = { binding = "AI" }\n');
  assert.deepEqual(parsed.sections, ['ai']);
  assert.deepEqual(parsed.remoteSections, []);
});

test('parser detects remote = true in an inline table inside an array', () => {
  const parsed = parseConfig('name = "x"\nkv_namespaces = [{ binding = "SPARKS", id = "p", remote = true }]\n');
  assert.ok(parsed.sections.includes('kv_namespaces'));
  assert.deepEqual(parsed.remoteSections, ['kv_namespaces']);
});

test('parser does not mistake a remote-ish key for remote = true', () => {
  const parsed = parseConfig('name = "x"\n[ai]\nremote_hint = true\nnot_remote = true\n');
  assert.deepEqual(parsed.remoteSections, []);
});

test('parser records dotted top-level keys as their section and attributes remote', () => {
  const parsed = parseConfig('name = "x"\nai.binding = "AI"\nai.remote = true\n');
  assert.deepEqual(parsed.sections, ['ai']);
  assert.deepEqual(parsed.remoteSections, ['ai']);
  const noRemote = parseConfig('name = "x"\nai.binding = "AI"\n');
  assert.deepEqual(noRemote.sections, ['ai']);
  assert.deepEqual(noRemote.remoteSections, []);
});

test('parser records top-level route/routes keys as a routes section', () => {
  assert.deepEqual(parseConfig('name = "x"\nroute = "a.dev/*"\n').sections, ['routes']);
  assert.deepEqual(parseConfig('name = "x"\nroutes = ["a.dev/*"]\n').sections, ['routes']);
});

// --- Malformed JSON inputs ---------------------------------------------------

test('verify reports a malformed runtime-baseline.json as a named failure', () => {
  const root = frozenRepo();
  writeFileSync(join(root, BASELINE_FILE), '{ not json');
  const result = verify(root);
  assert.equal(result.ok, false);
  assert.match(result.violations.join(' '), /runtime-baseline\.json is not valid JSON/);
});

test('verify reports a malformed package-lock.json as a named failure', () => {
  const root = frozenRepo();
  writeFileSync(join(root, 'package-lock.json'), '{ not json');
  const result = verify(root);
  assert.equal(result.ok, false);
  assert.match(result.violations.join(' '), /package-lock\.json is not valid JSON/);
});

// --- check:config dry-run inspection ----------------------------------------

const DRY_RUN_ROOT = `Total Upload: 10.00 KiB / gzip: 3.00 KiB
Your Worker has access to the following bindings:
Binding                              Resource
env.AI                               AI
env.SPARKS (prod-id)                 KV Namespace
env.METER (NeuronMeter)              Durable Object
--dry-run: exiting now.
`;
const DRY_RUN_OFFLINE = DRY_RUN_ROOT.replace('env.AI                               AI\n', '');

test('inspectDryRun passes a clean root and offline transcript', () => {
  assert.deepEqual(inspectDryRun(DRY_RUN_ROOT, { expectAi: true }), []);
  assert.deepEqual(inspectDryRun(DRY_RUN_OFFLINE, { expectAi: false }), []);
});

test('inspectDryRun fails on WARNING and Unexpected fields (stderr merged)', () => {
  const warned = `▲ [WARNING] Processing wrangler.toml configuration:\n  - Unexpected fields found in observability field: "preview_urls"\n${DRY_RUN_ROOT}`;
  const problems = inspectDryRun(warned, { expectAi: true });
  assert.match(problems.join(' '), /emitted a WARNING/);
  assert.match(problems.join(' '), /unexpected config fields/);
});

test('inspectDryRun fails when env.AI presence disagrees with expectation', () => {
  assert.match(inspectDryRun(DRY_RUN_OFFLINE, { expectAi: true }).join(' '), /expected env\.AI/);
  assert.match(inspectDryRun(DRY_RUN_ROOT, { expectAi: false }).join(' '), /must not appear in the offline/);
});

test('inspectDryRun refuses to judge env.AI when no binding table was printed', () => {
  const problems = inspectDryRun('--dry-run: exiting now.\n', { expectAi: false });
  assert.match(problems.join(' '), /binding table not found/);
});

// --- CLI ---------------------------------------------------------------------

test('CLI verify exits 1 from a checkout path containing a space', () => {
  const parent = mkdtempSync(join(tmpdir(), 'oddspark baseline cli-'));
  temps.push(parent);
  const root = join(parent, 'a repo with spaces');
  mkdirSync(join(root, 'scripts'), { recursive: true });
  for (const [rel, content] of Object.entries(FILES)) {
    const path = join(root, rel);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
  const script = join(root, 'scripts', 'runtime-baseline.mjs');
  copyFileSync(join(HERE, 'runtime-baseline.mjs'), script);

  // No runtime-baseline.json in this fixture, so a CLI that actually runs must
  // exit 1. A no-op entry guard would exit 0 and pass CI while checking nothing.
  let exit = 0;
  let stderr = '';
  try {
    run(process.execPath, [script, 'verify'], { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  } catch (error) {
    exit = error.status;
    stderr = error.stderr ?? '';
  }
  assert.equal(exit, 1, 'CLI must run and fail, not silently no-op with exit 0');
  assert.match(stderr, /runtime-baseline\.json is missing/);
});

// --- Runner ------------------------------------------------------------------

let failed = 0;
for (const [name, fn] of tests) {
  try {
    fn();
    console.log(`ok   ${name}`);
  } catch (error) {
    failed += 1;
    console.error(`FAIL ${name}\n     ${error.message}`);
  }
}
for (const dir of temps) rmSync(dir, { recursive: true, force: true });
console.log(`\n${tests.length - failed}/${tests.length} baseline tests passed`);
process.exit(failed === 0 ? 0 : 1);
